### ISSUE TITLE
Hola Issues

### ISSUE THREAD

**Issue by masuero** [maestria-geotel-201902/unidad-0-asignacion-1-asig-conrstudio-issues-masuero#1]
Saludos, tuve algunas dificultades para encontrar las pestañas de commit y issues me parece que se trata del proceso de adaptacion al entorno de la herramienta.

**Comment by geofis** [comment]
Perfecto. Me parece que a todos nos ocurre lo mismo. Yo también me peleé intensamente, pero ahora me resulta indispensable esta herramienta.
